artificier:
  ros__parameters:
    bombs: ['bomb_0', 'bomb_1', 'bomb_2', 'bomb_3', 'bomb_4', 'bomb_5', 'bomb_6', 'bomb_7', 'bomb_8']
    codes: ['2345', '1211', '2183', '3214', '5656', '7532', '1936', '1145', '1243']
    global_fame: 'map'
