artificier:
  ros__parameters:
    bombs: ['bomb_0', 'bomb_1', 'bomb_2', 'bomb_3', 'bomb_4', 'bomb_5', 'bomb_6', 'bomb_7', 'bomb_8', 'bomb_9', 'bomb_10', 'bomb_11', 'bomb_12', 'bomb_13']
    codes: ['2345', '1212', '2283', '3214', '5556', '7531', '1936', '1145', '1243', '4566', '7679', '2345', '6787', '8656']
    global_fame: 'map'
