artificier:
  ros__parameters:
    bombs: ['bomb_0', 'bomb_1', 'bomb_2', 'bomb_3', 'bomb_4', 'bomb_5', 'bomb_6', 'bomb_7']
    codes: ['1234', '1111', '2143', '3214', '5656', '7532', '1926', '1145']
    global_frame: 'odom'
